### ISSUE TITLE
Is our "Fixer" class approach appropriate?

### ISSUE THREAD

**Issue by agstephens** [roocs/daops#1]
Please check whether the Fixer approach that we have implemented will be flexible enough to address all issues with CMIP5, CMIP6 and CORDEX data.

Use the ESMValTool repository to review examples of fixes that are needed. 

Do we need something more than: 
 - pre-processor
 - post-processor

**Comment by larsbuntemeyer** [comment]
Hey,
i just stumpled over this issue looking for CORDEX fixes. I collected some issues that i found working with the EURO-CORDEX ensemble here (https://github.com/euro-cordex/py-cordex/issues/17) and implemented some fixes here (https://github.com/euro-cordex/py-cordex/pull/35). I will try to have a look at your Fixer class approach, maybe i can contribute some fixes for CORDEX datasets.
