### ISSUE TITLE
Add unit tests for ResultsDB object

### ISSUE THREAD

**Issue by agstephens** [roocs/daops#105]
Create a unit tests module for the new `ResultsDB` class.

**Comment by alaniwi** [comment]
The following tests are coded:

 - `test_write_and_read`: write some rows, close the file, read them in again, check consistency
 - `test_write_and_read_while_open`: write some rows; while still open, after each row, read in data and check consistency and also that the correct number of rows are in the csv compared to the sqlite, based on how often to merge
 - `test_manual_merge`: write some rows; after every row, call the `merge_and_tidy` method explicitly; then read in data, check consistency, and also check that all the data has come from the csv and none from the sqlite
 - `test_dump_data`: write some rows; before closing, get an (unzipped) copy of the csv file and a dump of the sqlite db, and check that it agrees with hard-coded check strings.

Issue ready to close unless other tests would be useful.
