### ISSUE TITLE
Define API parameters for subset and average processes

### ISSUE THREAD

**Issue by agstephens** [roocs/daops#19]
Follow OGC good practice and other relevant services to define sensible inputs for spatial/temporal parameters etc.

Needs some research into existing services.

E.g. should time window look like?

"1999-01-01T00:00:00Z/2000-10-10T12:00:00Z"

**Comment by agstephens** [comment]
We need to think about the full stack, i.e. rooki, rook, daops and clisops. It is important to be:

- consistent between our own interfaces
- consistent with CDS interfaces (if possible)
- consistent with OGC interfaces (if possible)
- consistent with Xarray interfaces (if possible)
- pythonic - where appropriate
- extensible - where needed

**Comment by agstephens** [comment]
Start a Google Spreadsheet of signatures for our operations. Create a table that includes info on:

- required parameters
  - which code layers use each parameter
  - proposed name(s) and source(s)/rationale
  - proposed value formats
    - which will differ between different levels of the stack
- include:
  - OGC recommends "foo"
  - Xarray uses "baa"
  - CDS Toolbox uses "foobaa"

In terms of averaging - read the docs for Xarray averaging and make suggestions for the signature/functionality - but keep it simple :-) 

Document URLs to materials in a separate tab.

**Comment by agstephens** [comment]
Other sources to look at for params:

 - Spatio Temporal Asset Catalog (STAC)
 - OpenSearch (EO)
 - GeoJSON spec (for coordinate orders - points and box spec)

**Comment by ellesmith88** [comment]
Link to spreadsheet: https://docs.google.com/spreadsheets/d/16IwejQmPhVKeZCjfZDLzZA3PjUagUhD-zdSHl79wiuc/edit?usp=sharing

**Comment by agstephens** [comment]
This has been done so closing.
