### ISSUE TITLE
consolidate expects file path with DRS folder structure

### ISSUE THREAD

**Issue by cehbrecht** [roocs/daops#43]
* daops version: 0.3.0
* Python version:
* Operating System:

### Description

The consolidate function works for a dataset id:
```
parameterise(
collection='c3s-cmip5.output1.ICHEC.EC-EARTH.historical.day.atmos.day.r1i1p1.tas.latest', 
time='1850/1855')
```

... and files with DRS folder structure:
```
parameterise(
collection='/data/c3s-cmip5/output1/ICHEC/EC-EARTH/historical/day/atmos/day/r1i1p1/tas/latest/tas_day_EC-EARTH_historical_r1i1p1_18500101-18591231.nc', 
time='1850/1855')
```

But it fails when only the file name is given without the DRS folders:
```
parameterise(
collection='/data/tas_day_EC-EARTH_historical_r1i1p1_18500101-18591231.nc', 
time='1850/1855')
```

Error message:
```
p = parameterise(
collection='/data/tas_day_EC-EARTH_historical_r1i1p1_18500101-18591231.nc', 
time='1850/1855')
result = subset(**p)

ValueError: max() arg is an empty sequence
```

The results of `subset` only have the filename but not the DRS folder structure:
```
p = parameterise(collection='c3s-cmip5.output1.ICHEC.EC-EARTH.historical.day.atmos.day.r1i1p1.tas.latest', time='1850/1855')
result = subset(**p)
result.file_paths
Out[9]: ['./tas_day_EC-EARTH_historical_r1i1p1_18500101-18551229.nc']
```

When we chain the `subset` operators then the second `subset` operation will fail on the output generated by the first one.

### What I Did

Running in ipython:
```
In [1]: from daops.ops.subset import subset

In [2]: from roocs_utils.parameter import parameterise

In [3]: p = parameterise(collection='/Users/pingu/tmp/data/tas_day_EC-EARTH_historical_r1i1p1_18500101-18591231.nc', time='1850/1855')

In [4]: result = subset(**p)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-b4d4a92f06bc> in <module>
----> 1 result = subset(**p)

~/miniconda3/envs/rook/lib/python3.7/site-packages/daops/ops/subset.py in subset(collection, time, area, level, output_dir, output_type, split_method, file_namer)
     59 
     60     collection = consolidate.consolidate(
---> 61         parameters.get("collection"), time=parameters.get("time")
     62     )
     63 

~/miniconda3/envs/rook/lib/python3.7/site-packages/daops/utils/consolidate.py in consolidate(collection, **kwargs)
     79         # convert dset to ds_id to work with elasticsearch index
     80         if not dset.count(".") > 6:
---> 81             dset = convert_to_ds_id(dset)
     82 
     83         if "time" in kwargs:

~/miniconda3/envs/rook/lib/python3.7/site-packages/daops/utils/consolidate.py in convert_to_ds_id(dset)
     48     elif os.path.isfile(dset) or dset.endswith(".nc"):
     49         dset = dset.split("/")
---> 50         i = max(loc for loc, val in enumerate(dset) if val.lower() in projects)
     51         ds_id = ".".join(dset[i:-1])
     52         return ds_id

ValueError: max() arg is an empty sequence
```

**Comment by cehbrecht** [comment]
If we need the dataset id for lookups can we get it also from the attributes in the netcdf header?

**Comment by agstephens** [comment]
Hi @cehbrecht, this is an interesting issue. I hadn't realised this would happen even though it is obvious in hindsight. 

My first thought is _do we need to use daops after the first operation in a workflow?_
Maybe the _fixing_ is only relevant to the first processing stage. If that is the case, then you _can_ safely send the path to the netcdf file to `clisops` and it should work.

@ellesmith88 - what do you think?

**Comment by ellesmith88** [comment]
@agstephens @cehbrecht I think you're right that `daops` is only needed for the first process. I think that would probably be the best fix. 

We could use the inventory with the file names at a later date to find the file and get the dataset id?

**Comment by cehbrecht** [comment]
> @agstephens @cehbrecht I think you're right that `daops` is only needed for the first process. I think that would probably be the best fix to then pass to `clisops`.
> 
> We could use the inventory with the file names at a later date to find the file and get the dataset id?

Ok ... sounds reasonable. I will try to tweak the workflow into this. Probably we want to move the workflow/orchestrate function to daops at a later stage.

**Comment by cehbrecht** [comment]
fixed in version on master. Tested in https://github.com/roocs/rook/pull/71
