### ISSUE TITLE
Check all occurrences of `open_dataset` and `open_xr_dataset` use `roocs-utils` version of the function

### ISSUE THREAD

**Issue by agstephens** [roocs/daops#68]
* daops version: current
* Python version: all
* Operating System: all

### Description

We have a common set of arguments that need to be sent to either of the `open` functions in `xarray`:

```
xr.open_dataset(...)
xr.open_mfdataset(...)
```

We need to make sure that all calls to these call:

`roocs_utils.xarray_utils.xarray_utils.open_xr_dataset(...)`

We need to review the `daops`, `dachar` and `clisops` code to check they are all doing this correctly. @ellesmith88, please can you take a look at this. Thanks

**Comment by agstephens** [comment]
I think I might have found out why this is an issue. In `daops/utils.core.py` we have:

```
    if apply_fixes:
        fix = fixer.Fixer(ds_id)
        if fix.pre_processor:
            for pre_process in fix.pre_processors:
                LOGGER.info(f"Loading data with pre_processor: {pre_process.__name__}")
        else:
            LOGGER.info(f"Loading data")

        ds = xr.open_mfdataset(
            file_paths,
            preprocess=fix.pre_processor,
            use_cftime=True,
            combine="by_coords",
        )

        if fix.post_processors:
            for post_process in fix.post_processors:
                func, operands = post_process
                LOGGER.info(f"Running post-processing function: {func.__name__}")
                ds = func(ds, **operands)

    else:
        ds = open_xr_dataset(file_paths)
```

I think that both clauses should call `open_xr_dataset(...)` but we should allow `**kwargs` to be sent to the function, so that you can extend the call but you always get the default arguments set that are common. 

NOTE: I might be confused so please double-check I'm not making a daft suggestion here.

**Comment by ellesmith88** [comment]
@agstephens Yes that make sense, I'll change this. Was there a particular issue that it was causing?

**Comment by agstephens** [comment]
@ellesmith88 I needed to use `decode_timedelta=False` but noticed that it needed changing in roocs utils and daops. So that made me think (a) we need to move the daops call over to using the generic version but (b) for future proofing it would be neat to be able to send extra kwargs in if we had special cases.

Please set `decode_timedelta=False` as a default in the roocs utils function.

**Comment by ellesmith88** [comment]
Done
