### ISSUE TITLE
Can we delete reference to "orchestrate"?

### ISSUE THREAD

**Issue by agstephens** [roocs/daops#71]
Hi @ellesmith88, I note that we have these empty modules:

https://github.com/roocs/daops/blob/master/tests/test_operations/test_orchestrate.py
https://github.com/roocs/daops/blob/master/daops/ops/orchestrate.py

Can they be deleted?

**Comment by ellesmith88** [comment]
@agstephens yes, they can be deleted! Shall I do it?
