### ISSUE TITLE
Could decadal fixes derive leadtime values on-the-fly?

### ISSUE THREAD

**Issue by agstephens** [roocs/daops#79]
* daops version: branch: decadal-fixes
* Python version: all
* Operating System: all

### Description

We have a system for generating fixes for adding the lead time variable, which uses:

https://github.com/roocs/daops/blob/decadal_fixes/daops/data_utils/coord_utils.py#L47-L76

For each fix, we include a string that includes a list of values, e.g.:

```
            "fix_id": "AddCoordFix",
            "operands": {
                "var_id": "leadtime",
                "value": "15,45,74,105,135,166,196,227,258,288,319,349,380,410,439,470,500,531,561,592,623,653,684,714,745,775,804,835,865,896,926,957,988,1018,1049,1079,1110,
1140,1169,1200,1231,1262,1292,1323,1354,1384,1415,1445,1476,1506,1535,1566,1596,1627,1657,1688,1719,1749,1780,1810,1841,1871,1900,1931,1961,1992,2022,2053,2084,2114,2145,2175,
2206,2236,2265,2296,2326,2357,2387,2418,2449,2479,2510,2540,2571,2601,2630,2661,2692,2723,2753,2784,2815,2845,2876,2906,2937,2967,2996,3027,3057,3088,3118,3149,3180,3210,3241,
3271,3302,3332,3361,3392,3422,3453,3483,3514,3545,3575,3606,3636,3667,3697",
                "dim": [
                    "time"
                ],
                "dtype": "float64",
                "attrs": {
                    "long_name": "Time elapsed since the start of the forecast",
                    "standard_name": "forecast_period",
                    "units": "days"
                },
                "encoding": {
                    "dtype": "double"
                }
            },
            "source": {
                "name": "ceda",
                "version": "",
                "comments": "",
                "url": "https://github.com/cp4cds/c3s34g_master/tree/master/Decadal"
            }

```

An alternative would be to encode a rule that tells the fix function to lookup the required values and add them into the new coordinate variable. Instead of `value` being set as a list of values, it could be some kind of rule such as:

```
"value": "derive: daops.data_utils.time_utils._get_lead_times"
```

@ellesmith88  This might be overkill but it is probably worth a discussion.

**Comment by ellesmith88** [comment]
I've started to have a look at this but have come a potential issue:

Deriving `lead_times` and `reftime` both depend on having the `start_date` (which is the same as the `sub_experiment_id`). If this isn't in the netCDF file, I had been getting it from the `ds_id`. 

According to the initial rules we were given (https://github.com/roocs/34e-mngmt/issues/98) it is possible that `startdate`/`sub_experiment_id` won't be in the file, so we can't depend on getting them from there. 

This means that either a default time or the `ds_id` need to be passed to the `get_lead_times` / `get_reftime` functions, as we can't necessarily get it from the xarray dataset. At the moment the `ds_id` isn't passed through to the fix functions (those in `daops.data_utils`), so isn't available for me to use. 

Options I have thought of are:
* we could send the `ds_id` through to fix functions by default. I think this would help keep the fix templates generic. From a quick look this looks like its possible and relatively straightforward to do. 

* we could have a way of passing arguments through somehow with the "derive: daops.data_utils.time_utils.function" string. This would the templates would be dataset specific so maybe isn't worth doing.

If we do the first option and pass the `ds_id` through to the fix functions and implement this then there is the chance we might come across the same issue in future where the argument we need doesn't exist in the `ds_id` and would need to passed through by the template. 

@agstephens Hopefully that makes sense, what are your thoughts?

**Comment by agstephens** [comment]
Hi @ellesmith88, thinking about your first option...

> we could send the `ds_id` through to fix functions by default. I think this would help keep the fix templates generic. From a quick look this looks like its possible and relatively straightforward to do.

I'm going to make some assertions (please tell me if I'm wrong):
1. All fixes in `daops` and `dachar` are only meaningful in the context of a `ds_id`. 
2. Therefore, we will always have a `ds_id` available at the point where we want to look up the fix, in: https://github.com/roocs/daops/blob/master/daops/utils/core.py
3. There are no other places in the stack that would get fundamentally broken by changing the fix signature to: `fix(ds_id, ds, **operands)`

If that is true, then I like your idea. It may well be useful in other cases of fixes in the future.

**Comment by ellesmith88** [comment]
I think all of your points are correct, I'll implement this and see how it goes

**Comment by agstephens** [comment]
Hi @ellesmith88, is this now implemented? Can we close it? Thanks

**Comment by ellesmith88** [comment]
@agstephens yes this is done.

**Comment by agstephens** [comment]
Thanks @ellesmith88
